apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hello
spec:
  selector: 
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
        ports:
        - containerPort: 8080
          protocol: TCP
